# config/packages/knp_gaufrette.yaml
#knp_gaufrette:
#    stream_wrapper: ~
#    adapters:
#        user_avatar_adapter:
#            local:
#                directory: '%kernel.project_dir%/public/uploads/user/avatar'
#                create: true
#    filesystems:
#        user_avatar_fs:
#            adapter:  user_avatar_adapter
