vich_uploader:
    db_driver: orm
    mappings:
        user_avatar :
            uri_prefix: /uploads/user/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        project_logo:
            uri_prefix: /uploads/project/logo
            upload_destination: '%kernel.project_dir%/public/uploads/project/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        project_cover_photo:
            uri_prefix: /uploads/project/cover
            upload_destination: '%kernel.project_dir%/public/uploads/project/cover'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        project_file:
            uri_prefix: /uploads/project/file
            upload_destination: '%kernel.project_dir%/public/uploads/project/file'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        admin_avatar:
            uri_prefix: /uploads/admin/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/admin/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true


